version: '3.3'

services:
  backend:
    build: ./Proyecto-Codigo-Backend_CalidadDeSoftware_Poli-Collaboration/
    depends_on:
      - db
    expose:
      - 3000
    ports:
      - "3000:3000"

  frontend:
    build: ./Proyecto-Codigo-Frontend_CalidadDeSoftware_Poli-Collaboration/
    depends_on:
      - backend
    expose:
      - 8080
    ports:
      - "8080:8080"

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./databaseData:/var/lib/postgresql/data