import { Flex, Link } from '@chakra-ui/react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../components/resources/header';
import { useEffect } from 'react';
import Cookies from 'js-cookie';
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();

  useEffect(() => {
      router.push('signup');
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>Poli - Collaboration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div mt="50%">
          <Link href="/signup">Pagina Principal - Registrarse como estudiante</Link>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
